version: "3.9"

services:
  spring:
    container_name: hanbange_app
    image: yanjuicy/hanbange:latest
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - default
      - hanbange_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server
    networks:
      - default
      - hanbange_network

networks:
  hanbange_network:
    driver: bridge