version: "3.9"

services:
  redis_container:
    container_name: redis_boot
    image: redis:latest
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server
