version: "3.9"

services:
  spring:
    container_name: hanbange_app
    image: yanjuicy/hanbange:latest
    ports:
      - "80:8080"

  redis_container:
    container_name: redis_boot
    image: redis:latest
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server
