drop table if exists product CASCADE;
drop table if exists brand CASCADE;

create table brand (
    brand_id bigint generated by default as identity,
    brand_name varchar(255) not null,
    primary key (brand_id)
);

create table product (
    product_id bigint generated by default as identity,
    img varchar(255) not null,
    on_sale boolean not null,
    price bigint not null,
    name varchar(255) not null,
    sales integer not null,
    stock integer not null,
    brand_id bigint,
    primary key (product_id)
);

alter table product
    add constraint FKs6cydsualtsrprvlf2bb3lcam
    foreign key (brand_id)
    references brand;