name: CD

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  cd-pipeline:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
        # docker-compose 파일 배포
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/"

        # docker-compose 파일 실행
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            docker rm -f $(docker ps -qa)
            docker-compose pull
            docker-compose up -d --remove-orphans
            docker image prune -f
